// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentUsosServer.Database;

#nullable disable

namespace StudentUsosServer.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20250123202035_Push notifications 2")]
    partial class Pushnotifications2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("StudenckiUSOSAPI.Models.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stacktrace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInternalAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("StudenckiUSOSAPI.Models.User", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessTokenSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreationDateUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FcmTokensJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "first_name");

                    b.Property<string>("Installation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalAccessTokenSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastActiveDateUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "last_name");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "student_number");

                    b.Property<string>("USOSId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.HasKey("InternalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StudenckiUSOSAPI.Models.Usos.UsosExam", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Installation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizedCourseNameJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.ToTable("UsosExams");
                });
#pragma warning restore 612, 618
        }
    }
}
